# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8083
  servlet:
    context-path: /blindstick
spring:
  datasource:
    username: root
    password: Ghulalala123?
    url: jdbc:mysql://47.97.205.5:3306/blind_stick?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 47.97.205.5
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
    timeout: 5s
  application:
    name: io


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.blindstick.model
  configuration:
    map-underscore-to-camel-case: true


WaterService:
  port: 4001

my:
  config:
    exclude-uri:
      - /blindstick/login
      - /blindstick/getCode
      - /blindstick/register
      - /blindstick/test